version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./config.json:/app/config.json
    command: --host 0.0.0.0 --api_host host.docker.internal --level INFO

  chatbot-ui:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    environment:
      - OPENAI_API_HOST=http://gateway:8080
      - OPENAI_API_KEY=xxxxxxxx
    ports:
      - "3000:3000"
    depends_on:
      - gateway
