# Copyright (c) 2023-2024 Steve Castellotti
# This file is part of Urcuchillay and is released under the MIT License.
# See LICENSE file in the project root for full license information.

version: '3.8'

services:
  gateway:
    build: .
    restart: on-failure  # Gateway may time out waiting to connect to server if server is downloading a model
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_PATH:-./data}:/app/data
      - ${STORAGE_PATH:-./storage}:/app/storage
      - ${CONFIG_PATH:-./config.json}:/app/config.json
    command: --host 0.0.0.0 --api_host server --level INFO ${GATEWAY_ARGS:-}
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ${CONFIG_PATH:-./config.json}:/server/config.json
      - ${MODELS_PATH:-./models}:/server/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    cap_add:
      - SYS_RESOURCE
    environment:
      - USE_MLOCK=0
    command: --api_host 0.0.0.0 --api_port 8000 --level INFO ${GPU_LAYERS_ARGS:-}

  ui:
    image: ghcr.io/castellotti/urcuchillay-chat:main
    environment:
      - OPENAI_API_HOST=http://gateway:8080
      - OPENAI_API_KEY=xxxxxxxx
    ports:
      - "${UI_PORT:-3000}:3000"
    depends_on:
      - gateway
