# Copyright (c) 2023 Steve Castellotti
# This file is part of Urcuchillay and is released under the MIT License.
# See LICENSE file in the project root for full license information.

version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_PATH:-./data}:/app/data
      - ${STORAGE_PATH:-./storage}:/app/storage
      - ${CONFIG_PATH:-./config.json}:/app/config.json
    command: --host 0.0.0.0 --api_host host.docker.internal --level INFO ${GATEWAY_ARGS:-}

  chatbot-ui:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    environment:
      - OPENAI_API_HOST=http://gateway:8080
      - OPENAI_API_KEY=xxxxxxxx
    ports:
      - "${UI_PORT:-3000}:3000"
    depends_on:
      - gateway
